spring:
  application:
    name: schedule
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule?characterEncoding=utf8
    username: root
    password: 1234